#' Load multiple .csv and merge
#'
#' Loads all .csv file from specified location that has number before suffix.
#'
#' @param mypath path to folder with .csv files generated by Calc_Core_Clust_Perm.py
#' @return data.frame
multmerge <-  function(mypath){

  filenames <- list.files(
    path = mypath,
    full.names = TRUE)

  filenames <- grep(
    pattern = "[[:digit:]]{1,}.csv",
    x = filenames,
    value = TRUE)

  datalist <-  lapply(
    filenames,
    function(x){read.csv(
      file = x,
      header = TRUE,
      stringsAsFactors = FALSE)}
  )

  Reduce(function(x,y) {dplyr::full_join(x,y, by = "CombID")}, datalist)
}
