# Script gathering functions and data formatting and manipulations necessary to 
# plot core pangenome accumulation boxplot based on core_clusters_permutations.py 
# output .csv files

options(stringsAsFactors = FALSE)
library(dplyr)
library(tidyr)
library(ggplot2)

# FORMATTING FUNCTIONS

#' @param mypath path to folder with .csv files generated by 
#'     core_clusters_permutations.py
multmerge <-  function(mypath){
  
  filenames=list.files(path=mypath, full.names=TRUE)
  
  datalist = lapply(filenames, function(x){read.csv(file=x,header=T, 
                                                    stringsAsFactors = FALSE)})
  
  Reduce(function(x,y) {dplyr::full_join(x,y)}, datalist)
}

#' @param df dataframe, output of multmerge function
modify_colnames <- function(df){
  #placeholder for new colum names
  new_collnames <- vector()
  #logic
  for (col in colnames(df)){
  
    if (col == "CombID"){
      new_collnames <- c(new_collnames, col)
    }
    else if (nchar(col) == 2){
    
      new_collnames <- c(new_collnames, sub("^X", 0, col)) 
    }
    else if (nchar(col) > 2){
      new_collnames <- c(new_collnames, sub("^X", "", col))
    }
  }
  #overwrite colnames
  colnames(df) <- new_collnames
  df
}

#' @param df dataframe output of modify_colnames
#' @return dataframe used in subsequent core pangenome analysis
format_df <- function(df){
  df <- df[,order(names(df))]
  df <- tidyr::gather(
    df_clean,
    key = "CombID",
    value = "Count") %>%
    dplyr::filter(!is.na(Count))
  
  df$CombID <- as.integer(df$CombID)
  dplyr::mutate(df, Count = ifelse(CombID == 1, NA, Count))
}

# CALCULATING FUNCTIONS
analyze_median_IQR <- function(df){
  df %>% 
    group_by(CombID) %>% 
    summarise(no = n(),
              median = median(Count),
              IQR = IQR(Count, na.rm = TRUE)) %>% 
    arrange(median)
}

analyze_mean_sd <- function(df){
  df %>% 
    group_by(CombID) %>% 
    summarise(no = n(),
              mean = mean(Count),
              sd = sd(Count)) %>% 
    arrange(mean)
}

# PLOTTING FUNCTIONS
plot_median_IQR <- function(sum_df_median){
  plt <- ggplot(data = sum_df_median, 
                 mapping = aes(x= CombID, 
                               y = median, 
                               fill = as.factor(no)))+
    geom_point(alpha = 0.5, 
               size = 7, 
               shape = 23)+
    geom_errorbar(aes(ymax = median + IQR, 
                      ymin = median - IQR), 
                  position = "dodge", 
                  na.rm = TRUE)+
    theme_light(base_size=19)+
    theme(axis.text.x = element_text(size = 20, 
                                     color = "black", 
                                     face = "bold"),
          legend.title = element_text(size = 20, 
                                      color = "black", 
                                      face = "bold"),
          legend.text = element_text(size = 20, 
                                     color = "black", 
                                     face = "bold"),
          legend.text.align = 1,
          legend.position = c(0.8, 0.8))+
    labs(x="Number of genomes", 
         y="Median size of core pangenome",
         #legend title
         fill = "Median based on\nnumber of permutations:")+
    geom_line(aes(group=1), 
              size = 1.05)+
    ylim(500,3000)
  
  plt
}

plot_mean_sd <- function(sum_df_mean){
  plt <- ggplot(data = sum_df_mean, 
                 mapping = aes(x= CombID, 
                               y = mean, 
                               fill = as.factor(no)))+
    geom_point(alpha = 0.5, 
               size = 7, 
               shape = 23)+
    geom_errorbar(aes(ymax = mean + sd, 
                      ymin = mean - sd), 
                  position = "dodge", 
                  na.rm = TRUE)+
    theme_light(base_size=19)+
    theme(axis.text.x = element_text(size = 20, 
                                     color = "black", 
                                     face = "bold"),
          legend.title = element_text(size = 20, 
                                      color = "black", 
                                      face = "bold"),
          legend.text = element_text(size = 20, 
                                     color = "black", 
                                     face = "bold"),
          legend.text.align = 1,
          legend.position = c(0.8, 0.8))+
    labs(x="Number of genomes", 
         y="Average size of core pangenome",
         #legend title
         fill = "Mean based on\nnumber of permutations:")+
    geom_line(aes(group=1), 
              size = 1.05)+
    ylim(500,3000)+
    xlim(1,44)
  
  plt
}

# ACTUAL DATA MANIPULATIONS

mypath <- "./maxperm10000/" #path to core_clusters_permutations.py output
df <- multmerge(mypath)
df_clean <- modify_colnames(df)
df_clean <- format_df(df_clean)


df_clean_sum_median <- analyze_median_IQR(df_clean)
df_clean_sum_mean <- analyze_mean_sd(df_clean)

df_clean_sum_median$CombID <- as.numeric(df_clean_sum_median$CombID)
df_clean_sum_mean$CombID <- as.numeric(df_clean_sum_mean$CombID)

df_clean_sum$no <- as.character(df_clean_sum$no)
df_clean$CombID <- as.numeric(df_clean$CombID)

# PUBLICATION CORE ACCUMULATION PANGENOME BOXPLOT
boxplt_core <- ggplot(data = df_clean, 
                 mapping = aes(x= as.factor(CombID), 
                               y = Count, 
                               group=CombID
                               ))+
  geom_boxplot(outlier.alpha = .005)

boxplt_core_line <- boxplt_core + 
  geom_line(data = df_clean_sum_median, 
            aes(x = CombID, 
                y=median, 
                group = 1),
            size = 1.01,
            color = "red",
            alpha = 0.5)+
  labs(y = "Core pangenome size", x = "Number of genomes")+
  theme_light(base_size=19)+
  ylim(0,NA)

png("core_accumulation_boxplot.png", width = 1500, height = 1000)
plot(boxplt_core_line)
dev.off()

#DOTPLOTs
medianplt <- plot_median_IQR(df_clean_sum_median)

png("density_median.png", width = 1500, height = 1000)
print(medianplt)
dev.off()

meanplt <- plot_mean_sd(df_clean_sum_mean)
  
png("density_mean.png", width = 1500, height = 1000)
print(meanplot)
dev.off()

multiplot(meanplt, medianplt)
